version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_model:
    run: stata-mp:latest analysis/STATA_code.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log1: logs/cr_create_analysis_dataset.smcl 
        data1: output/data/tables.csv
        data2: output/data/cox_model_summary.dta
        figure1: output/figures/survcurv_imiddrugcategory_icu.svg
	figure2: output/figures/imiddrugcategory_graph.gph	figure3: output/figures/survcurv_imiddrugcategory_died.svg
	figure4: output/figures/survcurv_bowel_icu.svg
	figure5: output/figures/bowel_graph.gph
	figure6: output/figures/survcurv_bowel_died.svg
	figure7: output/figures/survcurv_skin_icu.svg
	figure8: output/figures/skin_graph.gph
	figure9: output/figures/survcurv_skin_died.svg
	figure10: output/figures/survcurv_joint_icu.svg
	figure11: output/figures/joint_graph.gph
	figure12: output/figures/survcurv_joint_died.svg
	figure13: output/figures/survcurv_imid_icu.svg
	figure14: output/figures/imid_graph.gph
	figure15: output/figures/survcurv_imid_died.svg

        